repos:
  - repo: local
    hooks:
      - id: commit-msg-hook
        name: Check commit message format
        entry: python3 scripts/commit_msg_checker.py
        language: system
        stages: [commit-msg]